# Table of Contents
 <p><div class="lev1"><a href="#Task-1.-Compiling-Ebola-Data"><span class="toc-item-num">Task 1.&nbsp;&nbsp;</span>Compiling Ebola Data</a></div>
 <div class="lev1"><a href="#Task-2.-RNA-Sequences"><span class="toc-item-num">Task 2.&nbsp;&nbsp;</span>RNA Sequences</a></div>
 <div class="lev1"><a href="#Task-3.-Class-War-in-Titanic"><span class="toc-item-num">Task 3.&nbsp;&nbsp;</span>Class War in Titanic</a></div></p>

In [107]:
DATA_FOLDER = 'Data/ebola' # Use the data folder provided in Tutorial 02 - Intro to Pandas.

## Task 1. Compiling Ebola Data

The `DATA_FOLDER/ebola` folder contains summarized reports of Ebola cases from three countries (Guinea, Liberia and Sierra Leone) during the recent outbreak of the disease in West Africa. For each country, there are daily reports that contain various information about the outbreak in several cities in each country.

Use pandas to import these data files into a single `Dataframe`.
Using this `DataFrame`, calculate for *each country*, the *daily average per month* of *new cases* and *deaths*.
Make sure you handle all the different expressions for *new cases* and *deaths* that are used in the reports.

In [108]:
# Write your answer here
import glob
import pandas as pd
import numpy as np
from datetime import datetime
pd.options.mode.chained_assignment = None  # default='warn', Mutes warnings when copying a slice from a DataFrame.

In [38]:
#IMPORT GUINEA DATA
path = 'Data/ebola/guinea_data'
allFiles = glob.glob(path +  "/*.csv")
guinea = pd.DataFrame()
guinea_list_ = []
for file_ in allFiles:
    df = pd.read_csv(file_)
    guinea_list_.append(df)
guinea = pd.concat(guinea_list_, ignore_index = True)

#IMPORT LIBERIA DATA
path = 'Data/ebola/liberia_data'
allFiles = glob.glob(path +  "/*.csv")
liberia = pd.DataFrame()
liberia_list_ = []
for file_ in allFiles:
    df = pd.read_csv(file_)
    liberia_list_.append(df)
liberia = pd.concat(liberia_list_, ignore_index = True)

#IMPORT SIERRA LEONE DATA
path = 'Data/ebola/sl_data'
allFiles = glob.glob(path +  "/*.csv")
sl = pd.DataFrame()
sl_list_ = []
for file_ in allFiles:
    df = pd.read_csv(file_)
    sl_list_.append(df)
sl = pd.concat(sl_list_, ignore_index = True)

In [39]:
guinea

,Beyla,Boffa,Conakry,Coyah,Dabola,Dalaba,Date,Description,Dinguiraye,Dubreka,...,Kouroussa,Lola,Macenta,Mzerekore,Nzerekore,Pita,Siguiri,Telimele,Totals,Yomou
0,NaN,0,5,NaN,0,NaN,2014-08-04,New cases of suspects,0,0,...,0,NaN,0,NaN,0,0,0,0,5,NaN
1,NaN,0,0,NaN,0,NaN,2014-08-04,New cases of probables,0,0,...,0,NaN,0,NaN,0,0,0,0,0,NaN
2,NaN,0,1,NaN,0,NaN,2014-08-04,New cases of confirmed,0,0,...,0,NaN,0,NaN,0,0,0,0,4,NaN
3,NaN,0,6,NaN,0,NaN,2014-08-04,Total new cases registered so far,0,0,...,0,NaN,0,NaN,0,0,0,0,9,NaN
4,NaN,0,9,NaN,0,NaN,2014-08-04,Total cases of suspects,0,0,...,0,NaN,0,NaN,0,0,0,0,11,NaN
5,NaN,5,8,NaN,3,NaN,2014-08-04,Total cases of probables,1,0,...,2,NaN,11,NaN,0,1,0,3,133,NaN
6,NaN,18,78,NaN,1,NaN,2014-08-04,Total cases of confirmed,0,0,...,2,NaN,28,NaN,4,1,6,23,351,NaN
7,NaN,23,95,NaN,4,NaN,2014-08-04,Cumulative (confirmed + probable + suspects),1,0,...,4,NaN,39,NaN,4,2,6,26,495,NaN
8,NaN,0,0,NaN,0,NaN,2014-08-04,New deaths registered today,0,0,...,0,NaN,0,NaN,0,0,0,0,2,NaN
9,NaN,0,0,NaN,0,NaN,2014-08-04,New deaths registered today (confirmed),0,0,...,0,NaN,0,NaN,0,0,0,0,2,NaN
10,NaN,0,0,NaN,0,NaN,2014-08-04,New deaths registered today (probables),0,0,...,0,NaN,0,NaN,0,0,0,0,0,NaN
11,NaN,0,0,NaN,0,NaN,2014-08-04,New deaths registered today (suspects),0,0,...,0,NaN,0,NaN,0,0,0,0,0,NaN
12,NaN,0,2,NaN,0,NaN,2014-08-04,Total deaths of suspects,0,0,...,0,NaN,0,NaN,0,0,0,0,2,NaN
13,NaN,5,8,NaN,3,NaN,2014-08-04,Total deaths of probables,1,0,...,2,NaN,11,NaN,0,1,0,3,133,NaN
14,NaN,11,32,NaN,1,NaN,2014-08-04,Total deaths of confirmed,0,0,...,1,NaN,18,NaN,1,1,3,7,228,NaN
15,NaN,16,42,NaN,4,NaN,2014-08-04,Total deaths (confirmed + probables + suspects),1,0,...,3,NaN,29,NaN,1,2,3,10,363,NaN
16,NaN,0,21,NaN,0,NaN,2014-08-04,Total PEC center today,0,0,...,0,NaN,0,NaN,0,0,2,0,31,NaN
17,NaN,0,10,NaN,0,NaN,2014-08-04,Total PEC center today (confirmed),0,0,...,0,NaN,0,NaN,0,0,2,0,18,NaN
18,NaN,0,0,NaN,0,NaN,2014-08-04,Total PEC center today (probables),0,0,...,0,NaN,0,NaN,0,0,0,0,0,NaN
19,NaN,0,11,NaN,0,NaN,2014-08-04,Total PEC center today (suspects),0,0,...,0,NaN,0,NaN,0,0,0,0,13,NaN
20,NaN,6,20,NaN,0,NaN,2014-08-04,Total of deaths in confirmed cases in CTE,0,0,...,0,NaN,10,NaN,0,0,2,5,138,NaN
21,NaN,7,34,NaN,0,NaN,2014-08-04,Total of cured in confirmed cases in CTE,0,0,...,0,NaN,8,NaN,0,0,0,9,89,NaN
22,NaN,10,48,NaN,1,NaN,2014-08-04,Number of male confirmed cases,0,0,...,1,NaN,14,NaN,2,0,6,6,161,NaN
23,NaN,8,30,NaN,0,NaN,2014-08-04,Number of female confirmed cases,0,0,...,1,NaN,14,NaN,2,1,0,17,190,NaN
24,NaN,3,4,NaN,1,NaN,2014-08-04,Number of male probables cases,0,0,...,2,NaN,5,NaN,0,1,0,1,52,NaN
25,NaN,2,4,NaN,2,NaN,2014-08-04,Number of female probables cases,1,0,...,0,NaN,6,NaN,0,0,0,2,81,NaN
26,NaN,0,5,NaN,0,NaN,2014-08-04,Number of male suspects cases,0,0,...,0,NaN,0,NaN,0,0,2,0,7,NaN
27,NaN,0,4,NaN,0,NaN,2014-08-04,Number of female suspects cases,0,0,...,0,NaN,0,NaN,0,0,0,0,6,NaN
28,NaN,13,57,NaN,2,NaN,2014-08-04,Total number of male cases,0,0,...,3,NaN,19,NaN,2,1,8,7,220,NaN
29,NaN,10,38,NaN,2,NaN,2014-08-04,Total number of female cases,1,0,...,1,NaN,20,NaN,2,1,0,19,277,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
684,NaN,NaN,2,NaN,NaN,NaN,2014-10-01,New cases of confirmed,NaN,NaN,...,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,6,NaN
685,0,0,17,0,0,0,2014-10-01,Total new cases registered so far,0,0,...,0,9,5,NaN,1,0,0,0,34,0
686,0,0,19,0,0,0,2014-10-01,Total cases of suspects,0,0,...,0,9,9,NaN,2,1,0,0,45,0
687,0,5,10,0,3,0,2014-10-01,Total cases of probables,1,0,...,2,0,16,NaN,17,1,0,3,177,0
688,2,19,170,12,1,6,2014-10-01,Total cases of confirmed,0,21,...,2,2,378,NaN,31,6,6,23,977,11
689,2,24,199,12,4,6,2014-10-01,Cumulative (confirmed + probable + suspects),1,21,...,4,11,403,NaN,50,8,6,26,1199,11
690,0,20,355,6,3,1,2014-10-01,Total suspected non-class cases,0,20,...,2,4,197,NaN,16,18,9,18,974,4
691,NaN,NaN,NaN,NaN,NaN,NaN,2014-10-01,New deaths registered,NaN,NaN,...,NaN,NaN,15,NaN,NaN,NaN,NaN,NaN,15,NaN
692,0,0,0,0,0,0,2014-10-01,Total deaths of suspects,0,0,...,0,0,0,NaN,0,0,0,0,0,0
693,0,5,10,0,3,0,2014-10-01,Total deaths of probables,1,0,...,2,0,16,NaN,17,1,0,3,177,0
694,1,11,68,5,1,0,2014-10-01,Total deaths of confirmed,0,7,...,2,2,230,NaN,15,2,3,7,562,5
695,0,16,78,5,4,0,2014-10-01,Total deaths (confirmed + probables + suspects),1,7,...,4,0,246,NaN,32,3,3,10,739,5
696,100%,67%,39%,42%,100%,0%,2014-10-01,Fatality rate for confirmed and probables,100%,33%,...,100%,100%,61%,NaN,64%,38%,50%,38%,62%,45%
697,NaN,NaN,2,NaN,NaN,NaN,2014-10-01,New cases of confirmed among health workers,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN
698,0,0,40,1,0,0,2014-10-01,Total case of confirmed among health workers,0,3,...,0,0,9,NaN,2,0,2,2,69,1
699,0,0,0,0,0,0,2014-10-01,New deaths registered among health workers,0,0,...,0,0,0,NaN,0,0,0,0,0,0
700,0,0,18,0,0,0,2014-10-01,Total deaths registered among health workers,0,1,...,0,0,7,NaN,1,0,0,1,35,1
701,NaN,NaN,15,NaN,NaN,NaN,2014-10-01,New admits to CTE so far,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25,NaN
702,0,0,48,0,0,0,2014-10-01,Total number of hospitalized cases in CTE,0,0,...,0,NaN,12,NaN,0,0,0,0,114,0
703,0,0,9,0,0,0,2014-10-01,Total number of exits from CTE,0,0,...,0,NaN,15,NaN,0,0,0,0,29,0
704,0,0,571,0,0,0,2014-10-01,Total number of admissions to CTE,0,0,...,0,NaN,27,NaN,0,0,13,41,1576,0
705,NaN,NaN,NaN,NaN,NaN,NaN,2014-10-01,New contacts registered so far,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
706,2,397,3319,116,69,34,2014-10-01,Total contacts registered from start date,0,341,...,94,0,1563,NaN,353,140,141,259,11772,56
707,929,0,825,98,0,34,2014-10-01,Number of contacts to follow today,0,49,...,0,0,1038,NaN,126,0,0,0,2661,0
708,29,0,778,98,0,20,2014-10-01,Number of contacts followed today,0,49,...,0,0,1038,NaN,126,0,0,0,2595,0
709,0,397,2494,17,69,0,2014-10-01,Number of contacts out of the track 21 days,0,292,...,94,0,525,NaN,227,140,141,259,9110,56
710,0,0,0,1,0,0,2014-10-01,Number of contacts lost to follow up,0,0,...,0,0,0,NaN,0,0,0,0,1,0
711,NaN,NaN,16,NaN,NaN,NaN,2014-10-01,Number of samples collected today,NaN,NaN,...,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,25,NaN
712,NaN,NaN,0,NaN,NaN,NaN,2014-10-01,Number of samples under test,NaN,NaN,...,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN
713,NaN,NaN,1171,NaN,NaN,NaN,2014-10-01,Total samples tested,NaN,NaN,...,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,2832,NaN

In [140]:
# Pick interresting cases
interest_desc = ['New cases of suspects','New cases of probables','New cases of confirmed','Total deaths of suspects',
                 'Total deaths of probables','Total deaths of confirmed']
interest_desc

['New cases of suspects',
 'New cases of probables',
 'New cases of confirmed',
 'Total deaths of suspects',
 'Total deaths of probables',
 'Total deaths of confirmed']

In [141]:
# Select interresting cases from the dataframe
filtered_guinea = guinea[guinea.Description.isin(interest_desc)].copy()

In [142]:
#fill null values with zeros
filtered_guinea = filtered_guinea.fillna(0)

In [143]:
#Filter the total  if total = nan => sum of all cities 
not_city = ['Date', 'Description', 'Totals'] 

#replace the total nan values with the corresponding sum of all cities
filtered_guinea.loc[pd.isnull(filtered_guinea['Totals']), 'Totals'] = filtered_guinea.drop(not_city, axis=1).astype(int).sum(axis=1)

In [144]:
# Select not cities collumns
filtered_guinea = filtered_guinea[not_city]
filtered_guinea

          Date                Description Totals
0   2014-08-04      New cases of suspects      5
1   2014-08-04     New cases of probables      0
2   2014-08-04     New cases of confirmed      4
12  2014-08-04   Total deaths of suspects      2
13  2014-08-04  Total deaths of probables    133
14  2014-08-04  Total deaths of confirmed    228
0   2014-08-26      New cases of suspects     18
1   2014-08-26     New cases of probables      0
2   2014-08-26     New cases of confirmed     10
10  2014-08-26   Total deaths of suspects      2
11  2014-08-26  Total deaths of probables    141
12  2014-08-26  Total deaths of confirmed    292
0   2014-08-27      New cases of suspects     12
1   2014-08-27     New cases of probables      0
2   2014-08-27     New cases of confirmed     10
10  2014-08-27   Total deaths of suspects      2
11  2014-08-27  Total deaths of probables    142
12  2014-08-27  Total deaths of confirmed    294
0   2014-08-30      New cases of suspects     15
1   2014-08-30     New cases of probables      0
2   2014-08-30     New cases of confirmed      9
10  2014-08-30   Total deaths of suspects      2
11  2014-08-30  Total deaths of probables    142
12  2014-08-30  Total deaths of confirmed    324
0   2014-08-31      New cases of suspects      9
1   2014-08-31     New cases of probables      8
2   2014-08-31     New cases of confirmed     29
10  2014-08-31   Total deaths of suspects      2
11  2014-08-31  Total deaths of probables    150
12  2014-08-31  Total deaths of confirmed    337
..         ...                        ...    ...
0   2014-09-23      New cases of suspects      4
1   2014-09-23     New cases of probables      0
2   2014-09-23     New cases of confirmed     25
10  2014-09-23   Total deaths of suspects      5
11  2014-09-23  Total deaths of probables    162
12  2014-09-23  Total deaths of confirmed    476
0   2014-09-24      New cases of suspects      8
1   2014-09-24     New cases of probables      0
2   2014-09-24     New cases of confirmed     20
10  2014-09-24   Total deaths of suspects      5
11  2014-09-24  Total deaths of probables    162
12  2014-09-24  Total deaths of confirmed    481
0   2014-09-26      New cases of suspects      2
1   2014-09-26     New cases of probables      7
2   2014-09-26     New cases of confirmed     10
10  2014-09-26   Total deaths of suspects    169
11  2014-09-26  Total deaths of probables    494
12  2014-09-26  Total deaths of confirmed    668
0   2014-09-30      New cases of suspects      4
1   2014-09-30     New cases of probables      0
2   2014-09-30     New cases of confirmed     11
10  2014-09-30   Total deaths of suspects      0
11  2014-09-30  Total deaths of probables    175
12  2014-09-30  Total deaths of confirmed    539
0   2014-10-01      New cases of suspects     28
1   2014-10-01     New cases of probables      0
2   2014-10-01     New cases of confirmed      6
10  2014-10-01   Total deaths of suspects      0
11  2014-10-01  Total deaths of probables    177
12  2014-10-01  Total deaths of confirmed    562

[132 rows x 3 columns]

In [145]:
filtered_guinea['Month'] = pd.DatetimeIndex(filtered_guinea['Date']).month
filtered_guinea['Year'] = pd.DatetimeIndex(filtered_guinea['Date']).year
filtered_guinea

          Date                Description Totals  Month  Year
0   2014-08-04      New cases of suspects      5      8  2014
1   2014-08-04     New cases of probables      0      8  2014
2   2014-08-04     New cases of confirmed      4      8  2014
12  2014-08-04   Total deaths of suspects      2      8  2014
13  2014-08-04  Total deaths of probables    133      8  2014
14  2014-08-04  Total deaths of confirmed    228      8  2014
0   2014-08-26      New cases of suspects     18      8  2014
1   2014-08-26     New cases of probables      0      8  2014
2   2014-08-26     New cases of confirmed     10      8  2014
10  2014-08-26   Total deaths of suspects      2      8  2014
11  2014-08-26  Total deaths of probables    141      8  2014
12  2014-08-26  Total deaths of confirmed    292      8  2014
0   2014-08-27      New cases of suspects     12      8  2014
1   2014-08-27     New cases of probables      0      8  2014
2   2014-08-27     New cases of confirmed     10      8  2014
10  2014-08-27   Total deaths of suspects      2      8  2014
11  2014-08-27  Total deaths of probables    142      8  2014
12  2014-08-27  Total deaths of confirmed    294      8  2014
0   2014-08-30      New cases of suspects     15      8  2014
1   2014-08-30     New cases of probables      0      8  2014
2   2014-08-30     New cases of confirmed      9      8  2014
10  2014-08-30   Total deaths of suspects      2      8  2014
11  2014-08-30  Total deaths of probables    142      8  2014
12  2014-08-30  Total deaths of confirmed    324      8  2014
0   2014-08-31      New cases of suspects      9      8  2014
1   2014-08-31     New cases of probables      8      8  2014
2   2014-08-31     New cases of confirmed     29      8  2014
10  2014-08-31   Total deaths of suspects      2      8  2014
11  2014-08-31  Total deaths of probables    150      8  2014
12  2014-08-31  Total deaths of confirmed    337      8  2014
..         ...                        ...    ...    ...   ...
0   2014-09-23      New cases of suspects      4      9  2014
1   2014-09-23     New cases of probables      0      9  2014
2   2014-09-23     New cases of confirmed     25      9  2014
10  2014-09-23   Total deaths of suspects      5      9  2014
11  2014-09-23  Total deaths of probables    162      9  2014
12  2014-09-23  Total deaths of confirmed    476      9  2014
0   2014-09-24      New cases of suspects      8      9  2014
1   2014-09-24     New cases of probables      0      9  2014
2   2014-09-24     New cases of confirmed     20      9  2014
10  2014-09-24   Total deaths of suspects      5      9  2014
11  2014-09-24  Total deaths of probables    162      9  2014
12  2014-09-24  Total deaths of confirmed    481      9  2014
0   2014-09-26      New cases of suspects      2      9  2014
1   2014-09-26     New cases of probables      7      9  2014
2   2014-09-26     New cases of confirmed     10      9  2014
10  2014-09-26   Total deaths of suspects    169      9  2014
11  2014-09-26  Total deaths of probables    494      9  2014
12  2014-09-26  Total deaths of confirmed    668      9  2014
0   2014-09-30      New cases of suspects      4      9  2014
1   2014-09-30     New cases of probables      0      9  2014
2   2014-09-30     New cases of confirmed     11      9  2014
10  2014-09-30   Total deaths of suspects      0      9  2014
11  2014-09-30  Total deaths of probables    175      9  2014
12  2014-09-30  Total deaths of confirmed    539      9  2014
0   2014-10-01      New cases of suspects     28     10  2014
1   2014-10-01     New cases of probables      0     10  2014
2   2014-10-01     New cases of confirmed      6     10  2014
10  2014-10-01   Total deaths of suspects      0     10  2014
11  2014-10-01  Total deaths of probables    177     10  2014
12  2014-10-01  Total deaths of confirmed    562     10  2014

[132 rows x 5 columns]

In [146]:
#Reshape Table 
filtered_guinea = (filtered_guinea.set_index(['Description', 'Year', 'Month', 'Date'])['Totals'].unstack('Description'))

In [147]:
filtered_guinea

Description           New cases of confirmed New cases of probables  \
Year Month Date
2014 8     2014-08-04                      4                      0
           2014-08-26                     10                      0
           2014-08-27                     10                      0
           2014-08-30                      9                      0
           2014-08-31                     29                      8
     9     2014-09-02                     14                      0
           2014-09-04                     17                      0
           2014-09-07                     11                      0
           2014-09-08                     11                      0
           2014-09-09                      7                      0
           2014-09-11                     13                      0
           2014-09-14                     14                     11
           2014-09-16                      6                      0
           2014-09-17                      6                      0
           2014-09-19                     12                      1
           2014-09-21                     17                      0
           2014-09-22                     14                      0
           2014-09-23                     25                      0
           2014-09-24                     20                      0
           2014-09-26                     10                      7
           2014-09-30                     11                      0
     10    2014-10-01                      6                      0

Description           New cases of suspects Total deaths of confirmed  \
Year Month Date
2014 8     2014-08-04                     5                       228
           2014-08-26                    18                       292
           2014-08-27                    12                       294
           2014-08-30                    15                       324
           2014-08-31                     9                       337
     9     2014-09-02                    11                       349
           2014-09-04                    13                       368
           2014-09-07                     5                       402
           2014-09-08                     5                       402
           2014-09-09                     9                       410
           2014-09-11                     9                       413
           2014-09-14                     0                       429
           2014-09-16                     4                       442
           2014-09-17                     4                       442
           2014-09-19                     3                       463
           2014-09-21                     1                       465
           2014-09-22                     5                       468
           2014-09-23                     4                       476
           2014-09-24                     8                       481
           2014-09-26                     2                       668
           2014-09-30                     4                       539
     10    2014-10-01                    28                       562

Description           Total deaths of probables Total deaths of suspects
Year Month Date
2014 8     2014-08-04                       133                        2
           2014-08-26                       141                        2
           2014-08-27                       142                        2
           2014-08-30                       142                        2
           2014-08-31                       150                        2
     9     2014-09-02                       150                        2
           2014-09-04                       151                        3
           2014-09-07                       151                        4
           2014-09-08                       151                        4
           2014-09-09                       151                        4
           2014-09-11                       151                        4
           2014-09-14                       162                        4
           2014-09-16                       161                        5
           2014-09-17                       161                        5
           2014-09-19                       162                        5
           2014-09-21                       162                        5
           2014-09-22                       162                        5
           2014-09-23                       162                        5
           2014-09-24                       162                        5
           2014-09-26                       494                      169
           2014-09-30                       175                        0
     10    2014-10-01                       177                        0

In [149]:
#TODO Calculate averages

In [119]:
[des for des in liberia.Variable.unique() if  ('new' in des.lower())]

['Newly reported deaths',
 'Newly reported contacts',
 'New admissions',
 'Newly Reported Cases in HCW',
 'Newly Reported deaths in HCW',
 'New Case/s (Suspected)',
 'New Case/s (Probable)',
 'New case/s (confirmed)']

In [120]:
[des for des in sl.variable.unique() if ('New' in des) or ('new' in des)]

['new_noncase',
 'new_suspected',
 'new_probable',
 'new_confirmed',
 'etc_new_admission',
 'etc_new_deaths',
 'etc_new_discharges',
 'new_contacts',
 'new_completed_contacts',
 'new_samples',
 'new_positive',
 'new_negative']

In [121]:
sl.variable.unique()

array(['population', 'new_noncase', 'new_suspected', 'new_probable',
       'new_confirmed', 'cum_noncase', 'cum_suspected', 'cum_probable',
       'cum_confirmed', 'death_suspected', 'death_probable',
       'death_confirmed', 'cfr', 'etc_new_admission',
       'etc_currently_admitted', 'etc_cum_admission', 'etc_new_deaths',
       'etc_cum_deaths', 'etc_new_discharges', 'etc_cum_discharges',
       'cum_contacts', 'cum_completed_contacts', 'contacts_followed',
       'new_contacts', 'contacts_healthy', 'contacts_ill',
       'contacts_not_seen', 'new_completed_contacts', 'percent_seen',
       'total_lab_samples', 'repeat_samples', 'new_samples',
       'new_positive', 'new_negative', 'pending', 'positive_corpse',
       'negative_corpse'], dtype=object)

## Task 2. RNA Sequences

In the `DATA_FOLDER/microbiome` subdirectory, there are 9 spreadsheets of microbiome data that was acquired from high-throughput RNA sequencing procedures, along with a 10<sup>th</sup> file that describes the content of each. 

Use pandas to import the first 9 spreadsheets into a single `DataFrame`.
Then, add the metadata information from the 10<sup>th</sup> spreadsheet as columns in the combined `DataFrame`.
Make sure that the final `DataFrame` has a unique index and all the `NaN` values have been replaced by the tag `unknown`.

In [79]:
# Write your answer here
import glob
import pandas as pd
import numpy as np
from datetime import datetime
pd.options.mode.chained_assignment = None  # default='warn', Mutes warnings when copying a slice from a DataFrame.

In [80]:
#IMPORT MICROBIOME DATA
path = 'Data/microbiome'
allFiles = glob.glob(path +  "/*.xls")
file_counter = 0
microbiome_dfs = []

for file_ in allFiles:
    if file_counter > 0:
        microbiome_file = pd.read_excel(file_, header=None)
        microbiome_file['BARCODE'] = 'MID'+ str(file_counter)
        microbiome_dfs.append(microbiome_file)
    file_counter += 1
    
microbiome = pd.concat(microbiome_dfs, ignore_index = True)

microbiome

                                                      0     1 BARCODE
0     Archaea "Crenarchaeota" Thermoprotei Desulfuro...     7    MID1
1     Archaea "Crenarchaeota" Thermoprotei Desulfuro...     2    MID1
2     Archaea "Crenarchaeota" Thermoprotei Sulfoloba...     3    MID1
3     Archaea "Crenarchaeota" Thermoprotei Thermopro...     3    MID1
4     Archaea "Euryarchaeota" "Methanomicrobia" Meth...     7    MID1
5     Archaea "Euryarchaeota" "Methanomicrobia" Meth...     1    MID1
6     Archaea "Euryarchaeota" "Methanomicrobia" Meth...     1    MID1
7     Archaea "Euryarchaeota" Archaeoglobi Archaeogl...     1    MID1
8     Archaea "Euryarchaeota" Archaeoglobi Archaeogl...     1    MID1
9     Archaea "Euryarchaeota" Halobacteria Halobacte...     1    MID1
10    Archaea "Euryarchaeota" Halobacteria Halobacte...     4    MID1
11    Archaea "Euryarchaeota" Halobacteria Halobacte...     1    MID1
12    Archaea "Euryarchaeota" Halobacteria Halobacte...     2    MID1
13    Archaea "Euryarchaeota" Halobacteria Halobacte...     4    MID1
14    Archaea "Euryarchaeota" Methanococci Methanoco...     1    MID1
15    Archaea "Euryarchaeota" Methanopyri Methanopyr...    12    MID1
16    Archaea "Euryarchaeota" Thermoplasmata Thermop...     2    MID1
17    Bacteria "Actinobacteria" Actinobacteria Actin...     2    MID1
18    Bacteria "Actinobacteria" Actinobacteria Actin...     1    MID1
19    Bacteria "Actinobacteria" Actinobacteria Actin...     1    MID1
20    Bacteria "Actinobacteria" Actinobacteria Actin...     1    MID1
21    Bacteria "Actinobacteria" Actinobacteria Actin...     2    MID1
22    Bacteria "Actinobacteria" Actinobacteria Actin...    53    MID1
23    Bacteria "Actinobacteria" Actinobacteria Actin...     1    MID1
24    Bacteria "Actinobacteria" Actinobacteria Actin...     2    MID1
25    Bacteria "Actinobacteria" Actinobacteria Actin...     3    MID1
26    Bacteria "Actinobacteria" Actinobacteria Actin...     1    MID1
27    Bacteria "Actinobacteria" Actinobacteria Actin...    99    MID1
28    Bacteria "Actinobacteria" Actinobacteria Actin...    17    MID1
29    Bacteria "Actinobacteria" Actinobacteria Actin...     2    MID1
...                                                 ...   ...     ...
2366  Bacteria "Proteobacteria" Gammaproteobacteria ...    10    MID9
2367  Bacteria "Proteobacteria" Gammaproteobacteria ...     1    MID9
2368  Bacteria "Proteobacteria" Gammaproteobacteria ...     1    MID9
2369  Bacteria "Proteobacteria" Gammaproteobacteria ...     1    MID9
2370  Bacteria "Proteobacteria" Gammaproteobacteria ...    12    MID9
2371  Bacteria "Proteobacteria" Gammaproteobacteria ...     4    MID9
2372  Bacteria "Proteobacteria" Gammaproteobacteria ...   805    MID9
2373  Bacteria "Proteobacteria" Gammaproteobacteria ...   862    MID9
2374  Bacteria "Proteobacteria" Gammaproteobacteria ...    12    MID9
2375  Bacteria "Proteobacteria" Gammaproteobacteria ...  3534    MID9
2376  Bacteria "Proteobacteria" Gammaproteobacteria ...     4    MID9
2377  Bacteria "Proteobacteria" Gammaproteobacteria ...     1    MID9
2378  Bacteria "Proteobacteria" Gammaproteobacteria ...    25    MID9
2379  Bacteria "Proteobacteria" Gammaproteobacteria ...     2    MID9
2380  Bacteria "Proteobacteria" Gammaproteobacteria ...     3    MID9
2381  Bacteria "Proteobacteria" Gammaproteobacteria ...     2    MID9
2382  Bacteria "Proteobacteria" Gammaproteobacteria ...     1    MID9
2383  Bacteria "Proteobacteria" Gammaproteobacteria ...     3    MID9
2384  Bacteria "Proteobacteria" Gammaproteobacteria ...     2    MID9
2385  Bacteria "Proteobacteria" Gammaproteobacteria ...     1    MID9
2386  Bacteria "Synergistetes" Synergistia Synergist...     3    MID9
2387  Bacteria "Tenericutes" Mollicutes Anaeroplasma...     1    MID9
2388  Bacteria "Tenericutes" Mollicutes Haloplasmata...    11    MID9
2389  Bacteria "Thermodesulfobacteria" Thermodesulfo...     1    MID9
2390  Bacteria "Thermodesulfobacteria" Thermodesulfo...     1    MID9
2391  Bacteria "Thermotogae" Thermotogae Thermotogal...    43    MID9
2392  Bacteria "Thermotogae" Thermotogae Thermotogal...    16    MID9
2393  Bacteria "Verrucomicrobia" Opitutae Opitutales...     1    MID9
2394  Bacteria Cyanobacteria Cyanobacteria  Chloropl...     1    MID9
2395  Bacteria Cyanobacteria Cyanobacteria  Chloropl...    10    MID9

[2396 rows x 3 columns]

In [81]:
metadata = pd.read_excel('Data/microbiome/metadata.xls')
metadata

  BARCODE               GROUP  SAMPLE
0    MID1  EXTRACTION CONTROL     NaN
1    MID2               NEC 1  tissue
2    MID3           Control 1  tissue
3    MID4               NEC 2  tissue
4    MID5           Control 2  tissue
5    MID6               NEC 1   stool
6    MID7           Control 1   stool
7    MID8               NEC 2   stool
8    MID9           Control 2   stool

In [82]:
microbiome = pd.merge(microbiome, metadata)

In [83]:
microbiome = microbiome.fillna('unknown')
microbiome

,0,1,BARCODE,GROUP,SAMPLE
0,"Archaea ""Crenarchaeota"" Thermoprotei Desulfuro...",7,MID1,EXTRACTION CONTROL,unknown
1,"Archaea ""Crenarchaeota"" Thermoprotei Desulfuro...",2,MID1,EXTRACTION CONTROL,unknown
2,"Archaea ""Crenarchaeota"" Thermoprotei Sulfoloba...",3,MID1,EXTRACTION CONTROL,unknown
3,"Archaea ""Crenarchaeota"" Thermoprotei Thermopro...",3,MID1,EXTRACTION CONTROL,unknown
4,"Archaea ""Euryarchaeota"" ""Methanomicrobia"" Meth...",7,MID1,EXTRACTION CONTROL,unknown
5,"Archaea ""Euryarchaeota"" ""Methanomicrobia"" Meth...",1,MID1,EXTRACTION CONTROL,unknown
6,"Archaea ""Euryarchaeota"" ""Methanomicrobia"" Meth...",1,MID1,EXTRACTION CONTROL,unknown
7,"Archaea ""Euryarchaeota"" Archaeoglobi Archaeogl...",1,MID1,EXTRACTION CONTROL,unknown
8,"Archaea ""Euryarchaeota"" Archaeoglobi Archaeogl...",1,MID1,EXTRACTION CONTROL,unknown
9,"Archaea ""Euryarchaeota"" Halobacteria Halobacte...",1,MID1,EXTRACTION CONTROL,unknown
10,"Archaea ""Euryarchaeota"" Halobacteria Halobacte...",4,MID1,EXTRACTION CONTROL,unknown
11,"Archaea ""Euryarchaeota"" Halobacteria Halobacte...",1,MID1,EXTRACTION CONTROL,unknown
12,"Archaea ""Euryarchaeota"" Halobacteria Halobacte...",2,MID1,EXTRACTION CONTROL,unknown
13,"Archaea ""Euryarchaeota"" Halobacteria Halobacte...",4,MID1,EXTRACTION CONTROL,unknown
14,"Archaea ""Euryarchaeota"" Methanococci Methanoco...",1,MID1,EXTRACTION CONTROL,unknown
15,"Archaea ""Euryarchaeota"" Methanopyri Methanopyr...",12,MID1,EXTRACTION CONTROL,unknown
16,"Archaea ""Euryarchaeota"" Thermoplasmata Thermop...",2,MID1,EXTRACTION CONTROL,unknown
17,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",2,MID1,EXTRACTION CONTROL,unknown
18,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",1,MID1,EXTRACTION CONTROL,unknown
19,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",1,MID1,EXTRACTION CONTROL,unknown
20,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",1,MID1,EXTRACTION CONTROL,unknown
21,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",2,MID1,EXTRACTION CONTROL,unknown
22,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",53,MID1,EXTRACTION CONTROL,unknown
23,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",1,MID1,EXTRACTION CONTROL,unknown
24,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",2,MID1,EXTRACTION CONTROL,unknown
25,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",3,MID1,EXTRACTION CONTROL,unknown
26,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",1,MID1,EXTRACTION CONTROL,unknown
27,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",99,MID1,EXTRACTION CONTROL,unknown
28,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",17,MID1,EXTRACTION CONTROL,unknown
29,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",2,MID1,EXTRACTION CONTROL,unknown
...,...,...,...,...,...
2366,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",10,MID9,Control 2,stool
2367,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",1,MID9,Control 2,stool
2368,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",1,MID9,Control 2,stool
2369,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",1,MID9,Control 2,stool
2370,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",12,MID9,Control 2,stool
2371,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",4,MID9,Control 2,stool
2372,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",805,MID9,Control 2,stool
2373,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",862,MID9,Control 2,stool
2374,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",12,MID9,Control 2,stool
2375,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",3534,MID9,Control 2,stool
2376,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",4,MID9,Control 2,stool
2377,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",1,MID9,Control 2,stool
2378,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",25,MID9,Control 2,stool
2379,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",2,MID9,Control 2,stool
2380,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",3,MID9,Control 2,stool
2381,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",2,MID9,Control 2,stool
2382,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",1,MID9,Control 2,stool
2383,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",3,MID9,Control 2,stool
2384,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",2,MID9,Control 2,stool
2385,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",1,MID9,Control 2,stool
2386,"Bacteria ""Synergistetes"" Synergistia Synergist...",3,MID9,Control 2,stool
2387,"Bacteria ""Tenericutes"" Mollicutes Anaeroplasma...",1,MID9,Control 2,stool
2388,"Bacteria ""Tenericutes"" Mollicutes Haloplasmata...",11,MID9,Control 2,stool
2389,"Bacteria ""Thermodesulfobacteria"" Thermodesulfo...",1,MID9,Control 2,stool
2390,"Bacteria ""Thermodesulfobacteria"" Thermodesulfo...",1,MID9,Control 2,stool
2391,"Bacteria ""Thermotogae"" Thermotogae Thermotogal...",43,MID9,Control 2,stool
2392,"Bacteria ""Thermotogae"" Thermotogae Thermotogal...",16,MID9,Control 2,stool
2393,"Bacteria ""Verrucomicrobia"" Opitutae Opitutales...",1,MID9,Control 2,stool
2394,Bacteria Cyanobacteria Cyanobacteria Chloropl...,1,MID9,Control 2,stool
2395,Bacteria Cyanobacteria Cyanobacteria Chloropl...,10,MID9,Control 2,stool

In [113]:
microbiome = microbiome.rename(columns={0: 'TAXON', 1: 'COUNT'})
microbiomeIndexedData = microbiome.set_index(['BARCODE', 'Taxon'])
microbiomeIndexedData = microbiomeIndexedData[['GROUP', 'SAMPLE', 'Count']] 
microbiomeIndexedData

                                                                         GROUP  \
BARCODE Taxon
MID1    Archaea "Crenarchaeota" Thermoprotei Desulfuroc...  EXTRACTION CONTROL
        Archaea "Crenarchaeota" Thermoprotei Desulfuroc...  EXTRACTION CONTROL
        Archaea "Crenarchaeota" Thermoprotei Sulfolobal...  EXTRACTION CONTROL
        Archaea "Crenarchaeota" Thermoprotei Thermoprot...  EXTRACTION CONTROL
        Archaea "Euryarchaeota" "Methanomicrobia" Metha...  EXTRACTION CONTROL
        Archaea "Euryarchaeota" "Methanomicrobia" Metha...  EXTRACTION CONTROL
        Archaea "Euryarchaeota" "Methanomicrobia" Metha...  EXTRACTION CONTROL
        Archaea "Euryarchaeota" Archaeoglobi Archaeoglo...  EXTRACTION CONTROL
        Archaea "Euryarchaeota" Archaeoglobi Archaeoglo...  EXTRACTION CONTROL
        Archaea "Euryarchaeota" Halobacteria Halobacter...  EXTRACTION CONTROL
        Archaea "Euryarchaeota" Halobacteria Halobacter...  EXTRACTION CONTROL
        Archaea "Euryarchaeota" Halobacteria Halobacter...  EXTRACTION CONTROL
        Archaea "Euryarchaeota" Halobacteria Halobacter...  EXTRACTION CONTROL
        Archaea "Euryarchaeota" Halobacteria Halobacter...  EXTRACTION CONTROL
        Archaea "Euryarchaeota" Methanococci Methanococ...  EXTRACTION CONTROL
        Archaea "Euryarchaeota" Methanopyri Methanopyra...  EXTRACTION CONTROL
        Archaea "Euryarchaeota" Thermoplasmata Thermopl...  EXTRACTION CONTROL
        Bacteria "Actinobacteria" Actinobacteria Actino...  EXTRACTION CONTROL
        Bacteria "Actinobacteria" Actinobacteria Actino...  EXTRACTION CONTROL
        Bacteria "Actinobacteria" Actinobacteria Actino...  EXTRACTION CONTROL
        Bacteria "Actinobacteria" Actinobacteria Actino...  EXTRACTION CONTROL
        Bacteria "Actinobacteria" Actinobacteria Actino...  EXTRACTION CONTROL
        Bacteria "Actinobacteria" Actinobacteria Actino...  EXTRACTION CONTROL
        Bacteria "Actinobacteria" Actinobacteria Actino...  EXTRACTION CONTROL
        Bacteria "Actinobacteria" Actinobacteria Actino...  EXTRACTION CONTROL
        Bacteria "Actinobacteria" Actinobacteria Actino...  EXTRACTION CONTROL
        Bacteria "Actinobacteria" Actinobacteria Actino...  EXTRACTION CONTROL
        Bacteria "Actinobacteria" Actinobacteria Actino...  EXTRACTION CONTROL
        Bacteria "Actinobacteria" Actinobacteria Actino...  EXTRACTION CONTROL
        Bacteria "Actinobacteria" Actinobacteria Actino...  EXTRACTION CONTROL
...                                                                        ...
MID9    Bacteria "Proteobacteria" Gammaproteobacteria O...           Control 2
        Bacteria "Proteobacteria" Gammaproteobacteria O...           Control 2
        Bacteria "Proteobacteria" Gammaproteobacteria O...           Control 2
        Bacteria "Proteobacteria" Gammaproteobacteria P...           Control 2
        Bacteria "Proteobacteria" Gammaproteobacteria P...           Control 2
        Bacteria "Proteobacteria" Gammaproteobacteria P...           Control 2
        Bacteria "Proteobacteria" Gammaproteobacteria P...           Control 2
        Bacteria "Proteobacteria" Gammaproteobacteria P...           Control 2
        Bacteria "Proteobacteria" Gammaproteobacteria P...           Control 2
        Bacteria "Proteobacteria" Gammaproteobacteria P...           Control 2
        Bacteria "Proteobacteria" Gammaproteobacteria T...           Control 2
        Bacteria "Proteobacteria" Gammaproteobacteria T...           Control 2
        Bacteria "Proteobacteria" Gammaproteobacteria T...           Control 2
        Bacteria "Proteobacteria" Gammaproteobacteria T...           Control 2
        Bacteria "Proteobacteria" Gammaproteobacteria X...           Control 2
        Bacteria "Proteobacteria" Gammaproteobacteria X...           Control 2
        Bacteria "Proteobacteria" Gammaproteobacteria X...           Control 2
        Bacteria "Proteobacteria" Gammaproteobacteria X...           Control 2
        Bacteria "Proteobacteria" Gammaproteobacteria X...           Control 2
        Bacteria "Proteobacteria" Gammaproteobacteria X...           Control 2
        Bacteria "Synergistetes" Synergistia Synergista...           Control 2
        Bacteria "Tenericutes" Mollicutes Anaeroplasmat...           Control 2
        Bacteria "Tenericutes" Mollicutes Haloplasmatal...           Control 2
        Bacteria "Thermodesulfobacteria" Thermodesulfob...           Control 2
        Bacteria "Thermodesulfobacteria" Thermodesulfob...           Control 2
        Bacteria "Thermotogae" Thermotogae Thermotogale...           Control 2
        Bacteria "Thermotogae" Thermotogae Thermotogale...           Control 2
        Bacteria "Verrucomicrobia" Opitutae Opitutales ...           Control 2
        Bacteria Cyanobacteria Cyanobacteria  Chloropla...           Control 2
        Bacteria Cyanobacteria Cyanobacteria  Chloropla...           Control 2

                                                             SAMPLE  Count
BARCODE Taxon
MID1    Archaea "Crenarchaeota" Thermoprotei Desulfuroc...  unknown      7
        Archaea "Crenarchaeota" Thermoprotei Desulfuroc...  unknown      2
        Archaea "Crenarchaeota" Thermoprotei Sulfolobal...  unknown      3
        Archaea "Crenarchaeota" Thermoprotei Thermoprot...  unknown      3
        Archaea "Euryarchaeota" "Methanomicrobia" Metha...  unknown      7
        Archaea "Euryarchaeota" "Methanomicrobia" Metha...  unknown      1
        Archaea "Euryarchaeota" "Methanomicrobia" Metha...  unknown      1
        Archaea "Euryarchaeota" Archaeoglobi Archaeoglo...  unknown      1
        Archaea "Euryarchaeota" Archaeoglobi Archaeoglo...  unknown      1
        Archaea "Euryarchaeota" Halobacteria Halobacter...  unknown      1
        Archaea "Euryarchaeota" Halobacteria Halobacter...  unknown      4
        Archaea "Euryarchaeota" Halobacteria Halobacter...  unknown      1
        Archaea "Euryarchaeota" Halobacteria Halobacter...  unknown      2
        Archaea "Euryarchaeota" Halobacteria Halobacter...  unknown      4
        Archaea "Euryarchaeota" Methanococci Methanococ...  unknown      1
        Archaea "Euryarchaeota" Methanopyri Methanopyra...  unknown     12
        Archaea "Euryarchaeota" Thermoplasmata Thermopl...  unknown      2
        Bacteria "Actinobacteria" Actinobacteria Actino...  unknown      2
        Bacteria "Actinobacteria" Actinobacteria Actino...  unknown      1
        Bacteria "Actinobacteria" Actinobacteria Actino...  unknown      1
        Bacteria "Actinobacteria" Actinobacteria Actino...  unknown      1
        Bacteria "Actinobacteria" Actinobacteria Actino...  unknown      2
        Bacteria "Actinobacteria" Actinobacteria Actino...  unknown     53
        Bacteria "Actinobacteria" Actinobacteria Actino...  unknown      1
        Bacteria "Actinobacteria" Actinobacteria Actino...  unknown      2
        Bacteria "Actinobacteria" Actinobacteria Actino...  unknown      3
        Bacteria "Actinobacteria" Actinobacteria Actino...  unknown      1
        Bacteria "Actinobacteria" Actinobacteria Actino...  unknown     99
        Bacteria "Actinobacteria" Actinobacteria Actino...  unknown     17
        Bacteria "Actinobacteria" Actinobacteria Actino...  unknown      2
...                                                             ...    ...
MID9    Bacteria "Proteobacteria" Gammaproteobacteria O...    stool     10
        Bacteria "Proteobacteria" Gammaproteobacteria O...    stool      1
        Bacteria "Proteobacteria" Gammaproteobacteria O...    stool      1
        Bacteria "Proteobacteria" Gammaproteobacteria P...    stool      1
        Bacteria "Proteobacteria" Gammaproteobacteria P...    stool     12
        Bacteria "Proteobacteria" Gammaproteobacteria P...    stool      4
        Bacteria "Proteobacteria" Gammaproteobacteria P...    stool    805
        Bacteria "Proteobacteria" Gammaproteobacteria P...    stool    862
        Bacteria "Proteobacteria" Gammaproteobacteria P...    stool     12
        Bacteria "Proteobacteria" Gammaproteobacteria P...    stool   3534
        Bacteria "Proteobacteria" Gammaproteobacteria T...    stool      4
        Bacteria "Proteobacteria" Gammaproteobacteria T...    stool      1
        Bacteria "Proteobacteria" Gammaproteobacteria T...    stool     25
        Bacteria "Proteobacteria" Gammaproteobacteria T...    stool      2
        Bacteria "Proteobacteria" Gammaproteobacteria X...    stool      3
        Bacteria "Proteobacteria" Gammaproteobacteria X...    stool      2
        Bacteria "Proteobacteria" Gammaproteobacteria X...    stool      1
        Bacteria "Proteobacteria" Gammaproteobacteria X...    stool      3
        Bacteria "Proteobacteria" Gammaproteobacteria X...    stool      2
        Bacteria "Proteobacteria" Gammaproteobacteria X...    stool      1
        Bacteria "Synergistetes" Synergistia Synergista...    stool      3
        Bacteria "Tenericutes" Mollicutes Anaeroplasmat...    stool      1
        Bacteria "Tenericutes" Mollicutes Haloplasmatal...    stool     11
        Bacteria "Thermodesulfobacteria" Thermodesulfob...    stool      1
        Bacteria "Thermodesulfobacteria" Thermodesulfob...    stool      1
        Bacteria "Thermotogae" Thermotogae Thermotogale...    stool     43
        Bacteria "Thermotogae" Thermotogae Thermotogale...    stool     16
        Bacteria "Verrucomicrobia" Opitutae Opitutales ...    stool      1
        Bacteria Cyanobacteria Cyanobacteria  Chloropla...    stool      1
        Bacteria Cyanobacteria Cyanobacteria  Chloropla...    stool     10

[2396 rows x 3 columns]

In [115]:
microbiomeIndexedData.index.is_unique

True

## Task 3. Class War in Titanic

Use pandas to import the data file `Data/titanic.xls`. It contains data on all the passengers that travelled on the Titanic.

In [85]:
from IPython.core.display import HTML
HTML(filename=DATA_FOLDER+'/titanic.html')

NameError: name 'DATA_FOLDER' is not defined

For each of the following questions state clearly your assumptions and discuss your findings:
1. Describe the *type* and the *value range* of each attribute. Indicate and transform the attributes that can be `Categorical`. 
2. Plot histograms for the *travel class*, *embarkation port*, *sex* and *age* attributes. For the latter one, use *discrete decade intervals*. 
3. Calculate the proportion of passengers by *cabin floor*. Present your results in a *pie chart*.
4. For each *travel class*, calculate the proportion of the passengers that survived. Present your results in *pie charts*.
5. Calculate the proportion of the passengers that survived by *travel class* and *sex*. Present your results in *a single histogram*.
6. Create 2 equally populated *age categories* and calculate survival proportions by *age category*, *travel class* and *sex*. Present your results in a `DataFrame` with unique index.

In [ ]:
# Write your answer here